version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build-and-run-unit-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Fail Fast
          when: on_fail
          command: |
            echo "Canceling workflow as a step resulted in failure"
            echo curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}"       
      - run:
          name: Install Nodejs/NPM
          command: |
            echo 'apt-get update -qq && apt-get install -qq --no-install-recommends nodejs npm' | sudo bash
      - run:
          name: Build and Test Modules
          command: mvn -B -DskipFrontend clean test-compile -T 1C -q
  run-it-test:
    parallelism: 5
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install Nodejs/NPM
          command: |
            echo 'apt-get update -qq && apt-get install -qq --no-install-recommends nodejs npm' | sudo bash
      - run:
          name: Show Versions
          command: |
            google-chrome --version
            chromedriver --version
            node --version
            npm --version
      - run:
          name: Install TB License
          command: |
            mkdir -p ~/.vaadin/
            echo '{"username":"manolo@vaadin.com","proKey":"pro-7c65d687-35db-4c7b-a6aa-1c7b5bcfddcd"}' > ~/.vaadin/proKey
      - run:
          name: Run ITs
          command:  |
            T="
            vaadin-button-flow-parent/vaadin-button-flow-integration-tests
            vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests
            vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests
            vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests
            vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests
            "
            mvn verify -Dtest=none -am -V -B -e -fae verify \
              -Dcom.vaadin.testbench.Parameters.testsInParallel=2 \
              -pl $(echo "$T" | circleci tests split | tr '\n' ',')

workflows:
  build-and-test:
    jobs:
      - build-and-run-unit-test
      - run-it-test


# version: 2.1
# orbs:
#   slack: circleci/slack@4.0.0

# jobs:
#   build:
#     working_directory: ~/circleci-demo-python-django
#     docker:
#       - image: circleci/python:3.6.4
#         environment:
#           PIPENV_VENV_IN_PROJECT: true
#           DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
#       - image: circleci/postgres:9.6.2
#         environment:
#           POSTGRES_USER: root
#           POSTGRES_DB: circle_test
#     steps:
#       - checkout
#       - run: postgres -V


            # echo mvn verify -Dtest=none -am -V -B -e -fae verify \
            #   -Dcom.vaadin.testbench.Parameters.testsInParallel=2 \
            #   -pl $(circleci tests glob '**/vaadin*integration-tests' | circleci tests split | tr '\n' ',#')   